dinosaur/dinosaur/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dinosaurOrigin/', include('dinosaurOrigin.urls', namespace='dinosaurOrigin')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^.*', include('main.urls')),
]

dinosaur/dinosaurOrigin/urls.py
from django.conf.urls import url
from dinosaurOrigin import views


urlpatterns = [
    url(r'^$', views.dinosaurOrigin, name='dinosaurOrigin'),
]

dinosaur/main/urls.py
from django.conf.urls import url
from main import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
]

dinosaur/dinosaurOrigin/models.py
from django.db import models

# Create your models here.

dinosaur/main/models.py
from django.db import models

# Create your models here.

dinosaur/dinosaurOrigin/views.py
from django.shortcuts import render



def dinosaurOrigin(request):
    '''
    Render the main page
    '''
    context = {}
    return render(request, 'dinosaurOrigin/dinosaurOrigin.html', context)

dinosaur/main/views.py
from django.shortcuts import render
import datetime


def main(request):
    '''
    Render the main page
    '''
    now = datetime.datetime.now()
    context = {"now":now}
    return render(request, 'main/main.html', context)

dinosaur/dinosaurOrigin/templates/dinosaurOrigin/dinosaurOrigin.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>恐龍</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'dinosaurOrigin/css/dinosaurOrigin.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    </ul>
    <h2><font color="blue">起源</font></h2>
    <img src="{% static 'dinosaurOrigin/img/dinosaur2.jpg' %}" alt="...">
    <p>恐龍與牠們的主龍類祖先在三疊紀中到晚期分開演化，接近2億3000萬年前，大約是二疊紀-三疊紀滅絕事件後約2000萬年，該次滅絕事件消滅了接近95%的地球生物物種[30][31]。對於早期恐龍始盜龍發現地層的放射線定年法檢驗，證實始盜龍生存於中三疊紀。古生物學家認為始盜龍的外表類似所有恐龍的共同祖先[32]；如果屬實，則顯示最早的恐龍應該是種小型、二足掠食動物[33]。在阿根廷的中三疊紀地層所發現的原始、類似恐龍的鳥頸類主龍，例如：馬拉鱷龍與Lagerpeton，也支持這個說法；已出土的化石證據顯示這群動物都為小型、二足掠食動物。</p>
    <p>原始恐龍的第一次適應演化發生於三疊紀的卡尼階與諾利階之間，極可能因為當時有許多優勢動物滅亡。在傳統的觀念裡，在三疊紀中期，恐龍與當時其他的陸地動物展開長時間的競爭，並取得優勢，但這是不可能的。根據化石紀錄，恐龍沒那麼早出現，且早期恐龍並非穩定的增加、多樣化，而是後來才急驟的大量演化；如果牠們與其他動物有過長時間競爭，應該會在化石紀錄中反映出來。恐龍在卡尼階時的數量非常稀少，僅佔陸地動物群的1~2%。在諾利階，數個動物群滅亡後，恐龍則佔了陸地動物群的50~90%。恐龍的直立步態過去被視為成功演化的關鍵，但現在已知有數個同時代的動物群也有直立步態，例如：堅蜥類、鳥鱷科、勞氏鱷類、以及數種鱷形超目動物。三疊紀後期是個生物劇變的時代，有許多植物、海生動物興起衰落，三疊紀後期的氣候也有巨大改變[15]。鑲嵌踝類主龍目前僅剩下鱷魚，但在三疊紀晚期，鑲嵌踝類主龍是群非常多樣化的演化支，包含：鳥鱷科、堅蜥目、植龍目、勞氏鱷目。在這群優勢物種存在下，恐龍存活到侏羅紀，並非生理、競爭上佔有優勢，而是面對滅絕事件的運氣問題[34]。</p>
  </body>
</html>

dinosaur/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>恐龍</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    </ul>
    <h2><font color="blue">恐龍時代</font></h2>
    {% include 'main/time.html' %}
    <img src="{% static 'main/img/dinosaur.png' %}" alt="...">
    <p>大約在距今2億年前，地球上各個地區的氣候十分穩定，到處是大片的森林，爬行動物繁殖迅速，種類日益增多。其中，恐龍作為爬行動物的代表，成為整個中生代的一代霸主。</p>
    <p>但是，在距今6500萬～7000萬年前，中生代末期，不可一世的一代霸主恐龍到了窮途末路，遭到了滅頂之災。在很短的時間裡，整個恐龍家族全部銷聲匿跡，成為地球史上一次最大的悲慘事件。出人意料的是，在中生代不引人注目的最原始的哺乳類、原始鳥類和蛇、龜等與恐龍不可「同日而語」的小型爬行動物，卻躲過了那場史無前例的生物大浩劫，頑強地生存下來，一代一代地繁衍生息。</p>
  </body>
</html>

dinosaur/main/templates/main/menu.html
<ul id="menu">
  <li><a href="{% url 'main:main' %}">恐龍時代</a></li>
  <li><a href="{% url 'dinosaurOrigin:dinosaurOrigin' %}">起源</a></li>
</ul>

dinosaur/main/templates/main/time.html
<ul id="time">
  <p>現在時間：{{ now|date:'Y-m-d H:i:s' }}</p>
</ul>